;----------------------------------------------------
;  SmartMeterMonitor Configuration File
;  [Configuaration for sysWORXX Pi-AM62x with HAT]
;----------------------------------------------------
;  2026/01/17 -rs
;----------------------------------------------------

[Settings]
;MbInterface = /dev/ttyUSB0
MbInterface = /dev/ttyS3
Baudrate = 9600
QueryInterval = 60                                      ; [sec]
InterDevPause = 0.25                                    ; [sec]
MqttBroker = 192.168.3.200:1883
DataTopic = SmartMeter/Data/<label>/Measurements        ; this topic is individualized for each device
StatTopic = SmartMeter/Status                           ; this topic refers to the app globally, not to an single device
JsonInfoLevel = 2

[Device001]
Type = SDM230
ModbusID = 10
Label = Flat_1

[Device002]
Type = SDM630
ModbusID = 20
Label = Flat_2

[Device003]
Type = SDM230
ModbusID = 21
Label = HeatPump

[GasMeter]
SensorGpio = 0
Elasticity = 3                                          ; stretch factor (in number of cycles) until a data record is sent even without changing counter value
CounterDelta = 2                                        ; minimal increase of counter value until a data record is sent
VolumeFactor = 0.01                                     ; 1 Imp = 0.01 m3
EnergyFactor = 0.1062255                                ; 1 Imp = 0.01 m3 => 11.5 kWh/m3 * 0.9237 * 0.01 = 0.1062255 kWh/Imp
RetainFile = /home/smm/SmartMeterMonitor/GasMeterRetain.dat
Label = NaturalGasMeter



